/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\models\city.glb -o src/components/City.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function City(props) {
  const { nodes, materials } = useGLTF('/models/city.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh name="group2056379575" geometry={nodes.group2056379575.geometry} material={materials.mat22} />
        <mesh name="group414357712" geometry={nodes.group414357712.geometry} material={materials.mat17} />
        <group name="group1620407527">
          <mesh name="mesh1620407527" geometry={nodes.mesh1620407527.geometry} material={materials.mat17} />
          <mesh name="mesh1620407527_1" geometry={nodes.mesh1620407527_1.geometry} material={materials.mat9} />
          <mesh name="mesh1620407527_2" geometry={nodes.mesh1620407527_2.geometry} material={materials.mat19} />
          <mesh name="mesh1620407527_3" geometry={nodes.mesh1620407527_3.geometry} material={materials.mat16} />
          <mesh name="mesh1620407527_4" geometry={nodes.mesh1620407527_4.geometry} material={materials.mat20} />
        </group>
        <mesh name="group727847865" geometry={nodes.group727847865.geometry} material={materials.mat13} />
        <mesh name="group1086968796" geometry={nodes.group1086968796.geometry} material={materials.mat7} />
        <mesh name="group680713391" geometry={nodes.group680713391.geometry} material={materials.mat16} />
        <group name="group932878423">
          <mesh name="mesh932878423" geometry={nodes.mesh932878423.geometry} material={materials.mat7} />
          <mesh name="mesh932878423_1" geometry={nodes.mesh932878423_1.geometry} material={materials.mat20} />
          <mesh name="mesh932878423_2" geometry={nodes.mesh932878423_2.geometry} material={materials.mat3} />
          <mesh name="mesh932878423_3" geometry={nodes.mesh932878423_3.geometry} material={materials.mat8} />
        </group>
        <mesh name="group2062560926" geometry={nodes.group2062560926.geometry} material={materials.mat16} />
        <group name="group126351928">
          <mesh name="mesh126351928" geometry={nodes.mesh126351928.geometry} material={materials.mat13} />
          <mesh name="mesh126351928_1" geometry={nodes.mesh126351928_1.geometry} material={materials.mat3} />
          <mesh name="mesh126351928_2" geometry={nodes.mesh126351928_2.geometry} material={materials.mat2} />
        </group>
        <mesh name="group1889838734" geometry={nodes.group1889838734.geometry} material={materials.mat12} />
        <group name="group2099700118">
          <mesh name="mesh2099700118" geometry={nodes.mesh2099700118.geometry} material={materials.mat7} />
          <mesh name="mesh2099700118_1" geometry={nodes.mesh2099700118_1.geometry} material={materials.mat22} />
        </group>
        <group name="group226365589">
          <mesh name="mesh226365589" geometry={nodes.mesh226365589.geometry} material={materials.mat22} />
          <mesh name="mesh226365589_1" geometry={nodes.mesh226365589_1.geometry} material={materials.mat2} />
        </group>
        <group name="group470365829">
          <mesh name="mesh470365829" geometry={nodes.mesh470365829.geometry} material={materials.mat6} />
          <mesh name="mesh470365829_1" geometry={nodes.mesh470365829_1.geometry} material={materials.mat21} />
          <mesh name="mesh470365829_2" geometry={nodes.mesh470365829_2.geometry} material={materials.mat20} />
          <mesh name="mesh470365829_3" geometry={nodes.mesh470365829_3.geometry} material={materials.mat3} />
        </group>
        <group name="group442762496">
          <mesh name="mesh442762496" geometry={nodes.mesh442762496.geometry} material={materials.mat19} />
          <mesh name="mesh442762496_1" geometry={nodes.mesh442762496_1.geometry} material={materials.mat14} />
        </group>
        <group name="group1892910826">
          <mesh name="mesh1892910826" geometry={nodes.mesh1892910826.geometry} material={materials.mat15} />
          <mesh name="mesh1892910826_1" geometry={nodes.mesh1892910826_1.geometry} material={materials.mat3} />
        </group>
        <mesh name="group691832941" geometry={nodes.group691832941.geometry} material={materials.mat15} />
        <group name="group1501873170">
          <mesh name="mesh1501873170" geometry={nodes.mesh1501873170.geometry} material={materials.mat12} />
          <mesh name="mesh1501873170_1" geometry={nodes.mesh1501873170_1.geometry} material={materials.mat10} />
          <mesh name="mesh1501873170_2" geometry={nodes.mesh1501873170_2.geometry} material={materials.mat9} />
          <mesh name="mesh1501873170_3" geometry={nodes.mesh1501873170_3.geometry} material={materials.mat8} />
        </group>
        <mesh name="group88018646" geometry={nodes.group88018646.geometry} material={materials.mat22} />
        <group name="group1082111208">
          <mesh name="mesh1082111208" geometry={nodes.mesh1082111208.geometry} material={materials.mat22} />
          <mesh name="mesh1082111208_1" geometry={nodes.mesh1082111208_1.geometry} material={materials.mat20} />
        </group>
        <group name="group908718868">
          <mesh name="mesh908718868" geometry={nodes.mesh908718868.geometry} material={materials.mat20} />
          <mesh name="mesh908718868_1" geometry={nodes.mesh908718868_1.geometry} material={materials.mat22} />
        </group>
        <group name="group2065613719">
          <mesh name="mesh2065613719" geometry={nodes.mesh2065613719.geometry} material={materials.mat20} />
          <mesh name="mesh2065613719_1" geometry={nodes.mesh2065613719_1.geometry} material={materials.mat22} />
        </group>
        <group name="group984693493">
          
          <mesh name="mesh984693493" geometry={nodes.mesh984693493.geometry}
          material={materials.mat20} />
          <mesh name="mesh984693493_1" geometry={nodes.mesh984693493_1.geometry} material={materials.mat22} />
        </group>
        <group name="group1748987001">
          <mesh name="mesh1748987001" geometry={nodes.mesh1748987001.geometry} material={materials.mat20} />
          <mesh name="mesh1748987001_1" geometry={nodes.mesh1748987001_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1413670021" geometry={nodes.group1413670021.geometry} material={materials.mat10} />
        <mesh name="group1292478617" geometry={nodes.group1292478617.geometry} material={materials.mat8} />
        <mesh name="group888813550" geometry={nodes.group888813550.geometry} material={materials.mat10} />
        <mesh name="group750141131" geometry={nodes.group750141131.geometry} material={materials.mat8} />
        <mesh name="group1609482893" geometry={nodes.group1609482893.geometry} material={materials.mat10} />
        <mesh name="group710396509" geometry={nodes.group710396509.geometry} material={materials.mat8} />
        <mesh name="group1985881325" geometry={nodes.group1985881325.geometry} material={materials.mat16} />
        <mesh name="group1406586557" geometry={nodes.group1406586557.geometry} material={materials.mat16} />
        <mesh name="group586972705" geometry={nodes.group586972705.geometry} material={materials.mat4} />
        <mesh name="group865637349" geometry={nodes.group865637349.geometry} material={materials.mat4} />
        <mesh name="group1346688743" geometry={nodes.group1346688743.geometry} material={materials.mat4} />
        <mesh name="group15668877" geometry={nodes.group15668877.geometry} material={materials.mat4} />
        <mesh name="group543029238" geometry={nodes.group543029238.geometry} material={materials.mat8} />
        <mesh name="group1572810205" geometry={nodes.group1572810205.geometry} material={materials.mat8} />
        <mesh name="group1264051455" geometry={nodes.group1264051455.geometry} material={materials.mat8} />
        <mesh name="group1694619797" geometry={nodes.group1694619797.geometry} material={materials.mat16} />
        <mesh name="group1874814520" geometry={nodes.group1874814520.geometry} material={materials.mat13} />
        <mesh name="group1864723542" geometry={nodes.group1864723542.geometry} material={materials.mat7} />
        <mesh name="group2067440347" geometry={nodes.group2067440347.geometry} material={materials.mat7} />
        <mesh name="group2080372011" geometry={nodes.group2080372011.geometry} material={materials.mat7} />
        <mesh name="group172467855" geometry={nodes.group172467855.geometry} material={materials.mat7} />
        <mesh name="group1857028265" geometry={nodes.group1857028265.geometry} material={materials.mat13} />
        <mesh name="group733224695" geometry={nodes.group733224695.geometry} material={materials.mat13} />
        <mesh name="group1998030372" geometry={nodes.group1998030372.geometry} material={materials.mat12} />
        <mesh name="group1639921841" geometry={nodes.group1639921841.geometry} material={materials.mat12} />
        <mesh name="group1498273787" geometry={nodes.group1498273787.geometry} material={materials.mat12} />
        <group name="group1680882446">
          <mesh name="mesh1680882446" geometry={nodes.mesh1680882446.geometry} material={materials.mat20} />
          <mesh name="mesh1680882446_1" geometry={nodes.mesh1680882446_1.geometry} material={materials.mat22} />
          <mesh name="mesh1680882446_2" geometry={nodes.mesh1680882446_2.geometry} material={materials.mat3} />
        </group>
        <mesh name="group1776510033" geometry={nodes.group1776510033.geometry} material={materials.mat16} />
        <mesh name="group1399863776" geometry={nodes.group1399863776.geometry} material={materials.mat12} />
        <mesh name="group1258426828" geometry={nodes.group1258426828.geometry} material={materials.mat14} />
        <mesh name="group1865140274" geometry={nodes.group1865140274.geometry} material={materials.mat14} />
        <mesh name="group475029708" geometry={nodes.group475029708.geometry} material={materials.mat14} />
        <mesh name="group1353696619" geometry={nodes.group1353696619.geometry} material={materials.mat14} />
        <mesh name="group40712154" geometry={nodes.group40712154.geometry} material={materials.mat14} />
        <mesh name="group640296601" geometry={nodes.group640296601.geometry} material={materials.mat14} />
        <mesh name="group1418271139" geometry={nodes.group1418271139.geometry} material={materials.mat14} />
        <mesh name="group522458781" geometry={nodes.group522458781.geometry} material={materials.mat14} />
        <mesh name="group467366901" geometry={nodes.group467366901.geometry} material={materials.mat21} />
        <mesh name="group1323048669" geometry={nodes.group1323048669.geometry} material={materials.mat13} />
        <mesh name="group441506543" geometry={nodes.group441506543.geometry} material={materials.mat8} />
        <group name="group1106848498">
          <mesh name="mesh1106848498" geometry={nodes.mesh1106848498.geometry} material={materials.mat0} />
          <mesh name="mesh1106848498_1" geometry={nodes.mesh1106848498_1.geometry} material={materials.mat20} />
        </group>
        <group name="group1780499532">
          <mesh name="mesh1780499532" geometry={nodes.mesh1780499532.geometry} material={materials.mat16} />
          <mesh name="mesh1780499532_1" geometry={nodes.mesh1780499532_1.geometry} material={materials.mat9} />
        </group>
        <group name="group1937543949">
          <mesh name="mesh1937543949" geometry={nodes.mesh1937543949.geometry} material={materials.mat16} />
          <mesh name="mesh1937543949_1" geometry={nodes.mesh1937543949_1.geometry} material={materials.mat7} />
        </group>
        <group name="group1124096706">
          <mesh name="mesh1124096706" geometry={nodes.mesh1124096706.geometry} material={materials.mat16} />
          <mesh name="mesh1124096706_1" geometry={nodes.mesh1124096706_1.geometry} material={materials.mat13} />
        </group>
        <mesh name="group524105105" geometry={nodes.group524105105.geometry} material={materials.mat16} />
        <mesh name="group1620878968" geometry={nodes.group1620878968.geometry} material={materials.mat8} />
        <mesh name="group1084844802" geometry={nodes.group1084844802.geometry} material={materials.mat9} />
        <mesh name="group868537852" geometry={nodes.group868537852.geometry} material={materials.mat13} />
        <mesh name="group516813704" geometry={nodes.group516813704.geometry} material={materials.mat20} />
        <mesh name="group101110207" geometry={nodes.group101110207.geometry} material={materials.mat14} />
        <mesh name="group2099187000" geometry={nodes.group2099187000.geometry} material={materials.mat9} />
        <mesh name="group1766597619" geometry={nodes.group1766597619.geometry} material={materials.mat9} />
        <mesh name="group1320926355" geometry={nodes.group1320926355.geometry} material={materials.mat9} />
        <mesh name="group951137749" geometry={nodes.group951137749.geometry} material={materials.mat9} />
        <mesh name="group262444250" geometry={nodes.group262444250.geometry} material={materials.mat9} />
        <mesh name="group600335053" geometry={nodes.group600335053.geometry} material={materials.mat9} />
        <mesh name="group1134130336" geometry={nodes.group1134130336.geometry} material={materials.mat9} />
        <mesh name="group2038653779" geometry={nodes.group2038653779.geometry} material={materials.mat9} />
        <mesh name="group1587370546" geometry={nodes.group1587370546.geometry} material={materials.mat9} />
        <mesh name="group651024463" geometry={nodes.group651024463.geometry} material={materials.mat9} />
        <mesh name="group665012737" geometry={nodes.group665012737.geometry} material={materials.mat9} />
        <mesh name="group60436686" geometry={nodes.group60436686.geometry} material={materials.mat9} />
        <mesh name="group221600017" geometry={nodes.group221600017.geometry} material={materials.mat9} />
        <mesh name="group1695095144" geometry={nodes.group1695095144.geometry} material={materials.mat9} />
        <mesh name="group1532230904" geometry={nodes.group1532230904.geometry} material={materials.mat9} />
        <mesh name="group1181506897" geometry={nodes.group1181506897.geometry} material={materials.mat9} />
        <mesh name="group1927059894" geometry={nodes.group1927059894.geometry} material={materials.mat9} />
        <mesh name="group1946522784" geometry={nodes.group1946522784.geometry} material={materials.mat9} />
        <mesh name="group2116089924" geometry={nodes.group2116089924.geometry} material={materials.mat9} />
        <mesh name="group47558302" geometry={nodes.group47558302.geometry} material={materials.mat9} />
        <mesh name="group769597487" geometry={nodes.group769597487.geometry} material={materials.mat9} />
        <mesh name="group1597569391" geometry={nodes.group1597569391.geometry} material={materials.mat9} />
        <mesh name="group56515508" geometry={nodes.group56515508.geometry} material={materials.mat3} />
        <mesh name="group2121824914" geometry={nodes.group2121824914.geometry} material={materials.mat8} />
        <mesh name="group1256814026" geometry={nodes.group1256814026.geometry} material={materials.mat10} />
        <mesh name="group1121734058" geometry={nodes.group1121734058.geometry} material={materials.mat15} />
        <group name="group1971168243">
          <mesh name="mesh1971168243" geometry={nodes.mesh1971168243.geometry} material={materials.mat9} />
          <mesh name="mesh1971168243_1" geometry={nodes.mesh1971168243_1.geometry} material={materials.mat19} />
        </group>
        <mesh name="group1143673223" geometry={nodes.group1143673223.geometry} material={materials.mat11} />
        <group name="group42259831">
          <mesh name="mesh42259831" geometry={nodes.mesh42259831.geometry} material={materials.mat19} />
          <mesh name="mesh42259831_1" geometry={nodes.mesh42259831_1.geometry} material={materials.mat9} />
        </group>
        <mesh name="group85822852" geometry={nodes.group85822852.geometry} material={materials.mat11} />
        <mesh name="group1472696258" geometry={nodes.group1472696258.geometry} material={materials.mat11} />
        <mesh name="group24584671" geometry={nodes.group24584671.geometry} material={materials.mat14} />
        <mesh name="group1003486860" geometry={nodes.group1003486860.geometry} material={materials.mat20} />
        <mesh name="group150241968" geometry={nodes.group150241968.geometry} material={materials.mat20} />
        <group name="group312989640">
          <mesh name="mesh312989640" geometry={nodes.mesh312989640.geometry} material={materials.mat14} />
          <mesh name="mesh312989640_1" geometry={nodes.mesh312989640_1.geometry} material={materials.mat3} />
        </group>
        <mesh name="group1841617065" geometry={nodes.group1841617065.geometry} material={materials.mat14} />
        <mesh name="group2012264116" geometry={nodes.group2012264116.geometry} material={materials.mat20} />
        <mesh name="group508754903" geometry={nodes.group508754903.geometry} material={materials.mat3} />
        <mesh name="group939338192" geometry={nodes.group939338192.geometry} material={materials.mat3} />
        <mesh name="group1593054381" geometry={nodes.group1593054381.geometry} material={materials.mat13} />
        <mesh name="group359087187" geometry={nodes.group359087187.geometry} material={materials.mat13} />
        <mesh name="group102774809" geometry={nodes.group102774809.geometry} material={materials.mat13} />
        <mesh name="group2107722866" geometry={nodes.group2107722866.geometry} material={materials.mat13} />
        <mesh name="group1638089409" geometry={nodes.group1638089409.geometry} material={materials.mat21} />
        <mesh name="group2142662702" geometry={nodes.group2142662702.geometry} material={materials.mat21} />
        <mesh name="group797205382" geometry={nodes.group797205382.geometry} material={materials.mat21} />
        <mesh name="group60091006" geometry={nodes.group60091006.geometry} material={materials.mat21} />
        <mesh name="group750828229" geometry={nodes.group750828229.geometry} material={materials.mat21} />
        <mesh name="group200889301" geometry={nodes.group200889301.geometry} material={materials.mat8} />
        <mesh name="group961430359" geometry={nodes.group961430359.geometry} material={materials.mat8} />
        <mesh name="group698589884" geometry={nodes.group698589884.geometry} material={materials.mat8} />
        <mesh name="group1479201752" geometry={nodes.group1479201752.geometry} material={materials.mat8} />
        <mesh name="group1528848347" geometry={nodes.group1528848347.geometry} material={materials.mat8} />
        <mesh name="group1526546155" geometry={nodes.group1526546155.geometry} material={materials.mat4} />
        <mesh name="group904729909" geometry={nodes.group904729909.geometry} material={materials.mat4} />
        <group name="group1122170750">
          <mesh name="mesh1122170750" geometry={nodes.mesh1122170750.geometry} material={materials.mat4} />
          <mesh name="mesh1122170750_1" geometry={nodes.mesh1122170750_1.geometry} material={materials.mat2} />
          <mesh name="mesh1122170750_2" geometry={nodes.mesh1122170750_2.geometry} material={materials.mat18} />
          <mesh name="mesh1122170750_3" geometry={nodes.mesh1122170750_3.geometry} material={materials.mat3} />
        </group>
        <mesh name="group609919743" geometry={nodes.group609919743.geometry} material={materials.mat1} />
        <mesh name="group157386536" geometry={nodes.group157386536.geometry} material={materials.mat1} />
        <mesh name="group795522403" geometry={nodes.group795522403.geometry} material={materials.mat7} />
        <mesh name="group1245600664" geometry={nodes.group1245600664.geometry} material={materials.mat7} />
        <mesh name="group55739721" geometry={nodes.group55739721.geometry} material={materials.mat13} />
        <mesh name="group624325729" geometry={nodes.group624325729.geometry} material={materials.mat13} />
        <mesh name="group259297882" geometry={nodes.group259297882.geometry} material={materials.mat5} />
        <mesh name="group911345688" geometry={nodes.group911345688.geometry} material={materials.mat7} />
        <mesh name="group562950462" geometry={nodes.group562950462.geometry} material={materials.mat7} />
        <mesh name="group1219566439" geometry={nodes.group1219566439.geometry} material={materials.mat7} />
        <mesh name="group663642523" geometry={nodes.group663642523.geometry} material={materials.mat7} />
        <mesh name="group567964394" geometry={nodes.group567964394.geometry} material={materials.mat7} />
        <mesh name="group64923815" geometry={nodes.group64923815.geometry} material={materials.mat7} />
        <mesh name="group2141153155" geometry={nodes.group2141153155.geometry} material={materials.mat7} />
        <mesh name="group122350609" geometry={nodes.group122350609.geometry} material={materials.mat7} />
        <mesh name="group1773794116" geometry={nodes.group1773794116.geometry} material={materials.mat7} />
        <mesh name="group660944614" geometry={nodes.group660944614.geometry} material={materials.mat7} />
        <mesh name="group1185755869" geometry={nodes.group1185755869.geometry} material={materials.mat7} />
        <mesh name="group1677070716" geometry={nodes.group1677070716.geometry} material={materials.mat7} />
        <group name="group1942059648">
          <mesh name="mesh1942059648" geometry={nodes.mesh1942059648.geometry} material={materials.mat7} />
          <mesh name="mesh1942059648_1" geometry={nodes.mesh1942059648_1.geometry} material={materials.mat15} />
        </group>
        <mesh name="group2147293245" geometry={nodes.group2147293245.geometry} material={materials.mat20} />
        <mesh name="group1421193879" geometry={nodes.group1421193879.geometry} material={materials.mat9} />
        <mesh name="group817846806" geometry={nodes.group817846806.geometry} material={materials.mat9} />
        <mesh name="group1137983878" geometry={nodes.group1137983878.geometry} material={materials.mat9} />
        <mesh name="group1765287927" geometry={nodes.group1765287927.geometry} material={materials.mat14} />
        <mesh name="group1864489442" geometry={nodes.group1864489442.geometry} material={materials.mat14} />
        <mesh name="group1797051622" geometry={nodes.group1797051622.geometry} material={materials.mat14} />
        <mesh name="group762748902" geometry={nodes.group762748902.geometry} material={materials.mat14} />
        <mesh name="group128466819" geometry={nodes.group128466819.geometry} material={materials.mat14} />
        <mesh name="group454942412" geometry={nodes.group454942412.geometry} material={materials.mat14} />
        <mesh name="group1028218531" geometry={nodes.group1028218531.geometry} material={materials.mat14} />
        <mesh name="group618450094" geometry={nodes.group618450094.geometry} material={materials.mat14} />
        <mesh name="group1669668552" geometry={nodes.group1669668552.geometry} material={materials.mat14} />
        <mesh name="group92377835" geometry={nodes.group92377835.geometry} material={materials.mat9} />
        <mesh name="group886828513" geometry={nodes.group886828513.geometry} material={materials.mat9} />
        <mesh name="group921285744" geometry={nodes.group921285744.geometry} material={materials.mat14} />
        <mesh name="group1686704755" geometry={nodes.group1686704755.geometry} material={materials.mat9} />
        <mesh name="group477270091" geometry={nodes.group477270091.geometry} material={materials.mat14} />
        <mesh name="group798545587" geometry={nodes.group798545587.geometry} material={materials.mat14} />
        <mesh name="group2041132653" geometry={nodes.group2041132653.geometry} material={materials.mat20} />
        <mesh name="group268677556" geometry={nodes.group268677556.geometry} material={materials.mat14} />
        <mesh name="group1082422202" geometry={nodes.group1082422202.geometry} material={materials.mat14} />
        <mesh name="group1753874170" geometry={nodes.group1753874170.geometry} material={materials.mat14} />
        <mesh name="group1738925954" geometry={nodes.group1738925954.geometry} material={materials.mat14} />
        <mesh name="group797665846" geometry={nodes.group797665846.geometry} material={materials.mat14} />
        <mesh name="group1470642122" geometry={nodes.group1470642122.geometry} material={materials.mat14} />
        <mesh name="group559594553" geometry={nodes.group559594553.geometry} material={materials.mat14} />
        <mesh name="group900634096" geometry={nodes.group900634096.geometry} material={materials.mat9} />
        <mesh name="group291881985" geometry={nodes.group291881985.geometry} material={materials.mat9} />
        <mesh name="group1003508232" geometry={nodes.group1003508232.geometry} material={materials.mat21} />
        <mesh name="group208655468" geometry={nodes.group208655468.geometry} material={materials.mat14} />
        <mesh name="group493694332" geometry={nodes.group493694332.geometry} material={materials.mat18} />
        <mesh name="group124321088" geometry={nodes.group124321088.geometry} material={materials.mat21} />
        <mesh name="group1070809099" geometry={nodes.group1070809099.geometry} material={materials.mat21} />
        <mesh name="group1257396414" geometry={nodes.group1257396414.geometry} material={materials.mat21} />
        <mesh name="group1391114563" geometry={nodes.group1391114563.geometry} material={materials.mat8} />
        <mesh name="group1464448322" geometry={nodes.group1464448322.geometry} material={materials.mat3} />
        <mesh name="group993735862" geometry={nodes.group993735862.geometry} material={materials.mat3} />
        <mesh name="group684377666" geometry={nodes.group684377666.geometry} material={materials.mat19} />
        <mesh name="group1631379365" geometry={nodes.group1631379365.geometry} material={materials.mat19} />
        <mesh name="group1428455456" geometry={nodes.group1428455456.geometry} material={materials.mat19} />
        <mesh name="group41957016" geometry={nodes.group41957016.geometry} material={materials.mat19} />
        <mesh name="group1940431739" geometry={nodes.group1940431739.geometry} material={materials.mat19} />
        <mesh name="group1496653941" geometry={nodes.group1496653941.geometry} material={materials.mat19} />
        <mesh name="group385987102" geometry={nodes.group385987102.geometry} material={materials.mat19} />
        <mesh name="group1911176560" geometry={nodes.group1911176560.geometry} material={materials.mat19} />
        <mesh name="group723952216" geometry={nodes.group723952216.geometry} material={materials.mat19} />
        <mesh name="group1674529371" geometry={nodes.group1674529371.geometry} material={materials.mat19} />
        <mesh name="group500989838" geometry={nodes.group500989838.geometry} material={materials.mat3} />
        <mesh name="group669578198" geometry={nodes.group669578198.geometry} material={materials.mat3} />
        <mesh name="group304139486" geometry={nodes.group304139486.geometry} material={materials.mat18} />
        <mesh name="group2037240451" geometry={nodes.group2037240451.geometry} material={materials.mat18} />
        <mesh name="group2085132497" geometry={nodes.group2085132497.geometry} material={materials.mat3} />
        <mesh name="group247945956" geometry={nodes.group247945956.geometry} material={materials.mat3} />
        <mesh name="group1230207693" geometry={nodes.group1230207693.geometry} material={materials.mat3} />
        <mesh name="group2035227387" geometry={nodes.group2035227387.geometry} material={materials.mat3} />
        <mesh name="group844372103" geometry={nodes.group844372103.geometry} material={materials.mat13} />
        <mesh name="group1164346816" geometry={nodes.group1164346816.geometry} material={materials.mat13} />
        <mesh name="group731115180" geometry={nodes.group731115180.geometry} material={materials.mat13} />
        <mesh name="group2146013245" geometry={nodes.group2146013245.geometry} material={materials.mat13} />
        <mesh name="group1210557889" geometry={nodes.group1210557889.geometry} material={materials.mat13} />
        <mesh name="group1066419342" geometry={nodes.group1066419342.geometry} material={materials.mat13} />
        <mesh name="group1193964737" geometry={nodes.group1193964737.geometry} material={materials.mat13} />
        <mesh name="group993141604" geometry={nodes.group993141604.geometry} material={materials.mat13} />
        <mesh name="group891167760" geometry={nodes.group891167760.geometry} material={materials.mat7} />
        <mesh name="group1664575033" geometry={nodes.group1664575033.geometry} material={materials.mat7} />
        <mesh name="group845326814" geometry={nodes.group845326814.geometry} material={materials.mat7} />
        <mesh name="group1169640308" geometry={nodes.group1169640308.geometry} material={materials.mat7} />
        <mesh name="group151959752" geometry={nodes.group151959752.geometry} material={materials.mat7} />
        <mesh name="group1314544456" geometry={nodes.group1314544456.geometry} material={materials.mat7} />
        <mesh name="group1464424685" geometry={nodes.group1464424685.geometry} material={materials.mat7} />
        <mesh name="group1880506347" geometry={nodes.group1880506347.geometry} material={materials.mat4} />
        <mesh name="group1573184345" geometry={nodes.group1573184345.geometry} material={materials.mat4} />
        <mesh name="group1568188021" geometry={nodes.group1568188021.geometry} material={materials.mat4} />
        <mesh name="group1787596049" geometry={nodes.group1787596049.geometry} material={materials.mat4} />
        <mesh name="group2047162039" geometry={nodes.group2047162039.geometry} material={materials.mat4} />
        <mesh name="group206528836" geometry={nodes.group206528836.geometry} material={materials.mat15} />
        <mesh name="group1880592623" geometry={nodes.group1880592623.geometry} material={materials.mat15} />
        <mesh name="group1843916533" geometry={nodes.group1843916533.geometry} material={materials.mat15} />
        <mesh name="group943336647" geometry={nodes.group943336647.geometry} material={materials.mat15} />
        <mesh name="group1951152715" geometry={nodes.group1951152715.geometry} material={materials.mat15} />
        <mesh name="group2026192871" geometry={nodes.group2026192871.geometry} material={materials.mat0} />
        <mesh name="group547319172" geometry={nodes.group547319172.geometry} material={materials.mat17} />
        <mesh name="group1830944184" geometry={nodes.group1830944184.geometry} material={materials.mat6} />
        <mesh name="group1744693932" geometry={nodes.group1744693932.geometry} material={materials.mat6} />
        <mesh name="group242284226" geometry={nodes.group242284226.geometry} material={materials.mat17} />
        <mesh name="group1847397043" geometry={nodes.group1847397043.geometry} material={materials.mat17} />
        <mesh name="group14204489" geometry={nodes.group14204489.geometry} material={materials.mat6} />
        <mesh name="group135234260" geometry={nodes.group135234260.geometry} material={materials.mat3} />
        <mesh name="group1720634340" geometry={nodes.group1720634340.geometry} material={materials.mat6} />
        <mesh name="group523951915" geometry={nodes.group523951915.geometry} material={materials.mat6} />
        <mesh name="group2099066497" geometry={nodes.group2099066497.geometry} material={materials.mat6} />
        <mesh name="group1383291985" geometry={nodes.group1383291985.geometry} material={materials.mat3} />
        <mesh name="group316979448" geometry={nodes.group316979448.geometry} material={materials.mat17} />
        <mesh name="group337424666" geometry={nodes.group337424666.geometry} material={materials.mat17} />
        <mesh name="group1703004556" geometry={nodes.group1703004556.geometry} material={materials.mat17} />
        <mesh name="group1325840211" geometry={nodes.group1325840211.geometry} material={materials.mat3} />
        <mesh name="group1127167855" geometry={nodes.group1127167855.geometry} material={materials.mat25} />
        <group name="group314485410">
          <mesh name="mesh314485410" geometry={nodes.mesh314485410.geometry} material={materials.mat6} />
          <mesh name="mesh314485410_1" geometry={nodes.mesh314485410_1.geometry} material={materials.mat20} />
        </group>
        <group name="group351618862">
          <mesh name="mesh351618862" geometry={nodes.mesh351618862.geometry} material={materials.mat6} />
          <mesh name="mesh351618862_1" geometry={nodes.mesh351618862_1.geometry} material={materials.mat18} />
        </group>
        <group name="group1127063720">
          <mesh name="mesh1127063720" geometry={nodes.mesh1127063720.geometry} material={materials.mat18} />
          <mesh name="mesh1127063720_1" geometry={nodes.mesh1127063720_1.geometry} material={materials.mat6} />
        </group>
        <mesh name="group251944486" geometry={nodes.group251944486.geometry} material={materials.mat6} />
        <mesh name="group314705383" geometry={nodes.group314705383.geometry} material={materials.mat6} />
        <mesh name="group416838217" geometry={nodes.group416838217.geometry} material={materials.mat6} />
        <mesh name="group1802874381" geometry={nodes.group1802874381.geometry} material={materials.mat7} />
        <mesh name="group700093952" geometry={nodes.group700093952.geometry} material={materials.mat13} />
        <mesh name="group1241103983" geometry={nodes.group1241103983.geometry} material={materials.mat13} />
        <mesh name="group1787663556" geometry={nodes.group1787663556.geometry} material={materials.mat13} />
        <mesh name="group55021070" geometry={nodes.group55021070.geometry} material={materials.mat13} />
        <mesh name="group1100348246" geometry={nodes.group1100348246.geometry} material={materials.mat13} />
        <mesh name="group475936151" geometry={nodes.group475936151.geometry} material={materials.mat13} />
        <mesh name="group1530364807" geometry={nodes.group1530364807.geometry} material={materials.mat13} />
        <mesh name="group1897230613" geometry={nodes.group1897230613.geometry} material={materials.mat13} />
        <mesh name="group1512008771" geometry={nodes.group1512008771.geometry} material={materials.mat13} />
        <mesh name="group992920988" geometry={nodes.group992920988.geometry} material={materials.mat5} />
        <group name="group1754984776">
          <mesh name="mesh1754984776" geometry={nodes.mesh1754984776.geometry} material={materials.mat5} />
          <mesh name="mesh1754984776_1" geometry={nodes.mesh1754984776_1.geometry} material={materials.mat14} />
          <mesh name="mesh1754984776_2" geometry={nodes.mesh1754984776_2.geometry} material={materials.mat19} />
        </group>
        <group name="group1597240921">
          <mesh name="mesh1597240921" geometry={nodes.mesh1597240921.geometry} material={materials.mat12} />
          <mesh name="mesh1597240921_1" geometry={nodes.mesh1597240921_1.geometry} material={materials.mat10} />
          <mesh name="mesh1597240921_2" geometry={nodes.mesh1597240921_2.geometry} material={materials.mat9} />
        </group>
        <group name="group2015324951">
          <mesh name="mesh2015324951" geometry={nodes.mesh2015324951.geometry} material={materials.mat9} />
          <mesh name="mesh2015324951_1" geometry={nodes.mesh2015324951_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group1465108883" geometry={nodes.group1465108883.geometry} material={materials.mat16} />
        <mesh name="group1740676640" geometry={nodes.group1740676640.geometry} material={materials.mat13} />
        <mesh name="group1391233971" geometry={nodes.group1391233971.geometry} material={materials.mat17} />
        <mesh name="group1297668711" geometry={nodes.group1297668711.geometry} material={materials.mat3} />
        <mesh name="group620383973" geometry={nodes.group620383973.geometry} material={materials.mat9} />
        <mesh name="group1177090369" geometry={nodes.group1177090369.geometry} material={materials.mat9} />
        <mesh name="group1860358994" geometry={nodes.group1860358994.geometry} material={materials.mat9} />
        <mesh name="group878678446" geometry={nodes.group878678446.geometry} material={materials.mat9} />
        <mesh name="group506627292" geometry={nodes.group506627292.geometry} material={materials.mat3} />
        <mesh name="group1814875046" geometry={nodes.group1814875046.geometry} material={materials.mat3} />
        <mesh name="group1030007046" geometry={nodes.group1030007046.geometry} material={materials.mat3} />
        <mesh name="group124364111" geometry={nodes.group124364111.geometry} material={materials.mat3} />
        <mesh name="group728602477" geometry={nodes.group728602477.geometry} material={materials.mat3} />
        <mesh name="group1957333004" geometry={nodes.group1957333004.geometry} material={materials.mat13} />
        <mesh name="group1720232977" geometry={nodes.group1720232977.geometry} material={materials.mat13} />
        <mesh name="group1975520359" geometry={nodes.group1975520359.geometry} material={materials.mat17} />
        <mesh name="group1453221850" geometry={nodes.group1453221850.geometry} material={materials.mat21} />
        <mesh name="group1402842132" geometry={nodes.group1402842132.geometry} material={materials.mat8} />
        <mesh name="group148017623" geometry={nodes.group148017623.geometry} material={materials.mat8} />
        <mesh name="group2042011293" geometry={nodes.group2042011293.geometry} material={materials.mat8} />
        <mesh name="group1613865620" geometry={nodes.group1613865620.geometry} material={materials.mat13} />
        <mesh name="group1528223782" geometry={nodes.group1528223782.geometry} material={materials.mat7} />
        <mesh name="group385348057" geometry={nodes.group385348057.geometry} material={materials.mat7} />
        <mesh name="group647559403" geometry={nodes.group647559403.geometry} material={materials.mat7} />
        <mesh name="group102274334" geometry={nodes.group102274334.geometry} material={materials.mat7} />
        <mesh name="group912519134" geometry={nodes.group912519134.geometry} material={materials.mat7} />
        <mesh name="group904430728" geometry={nodes.group904430728.geometry} material={materials.mat7} />
        <mesh name="group1674520274" geometry={nodes.group1674520274.geometry} material={materials.mat5} />
        <mesh name="group1579184403" geometry={nodes.group1579184403.geometry} material={materials.mat5} />
        <mesh name="group930640138" geometry={nodes.group930640138.geometry} material={materials.mat5} />
        <mesh name="group1615729652" geometry={nodes.group1615729652.geometry} material={materials.mat5} />
        <mesh name="group974648111" geometry={nodes.group974648111.geometry} material={materials.mat15} />
        <mesh name="group573343453" geometry={nodes.group573343453.geometry} material={materials.mat15} />
        <mesh name="group1883979655" geometry={nodes.group1883979655.geometry} material={materials.mat15} />
        <mesh name="group1597084126" geometry={nodes.group1597084126.geometry} material={materials.mat21} />
        <group name="group676558152">
          <mesh name="mesh676558152" geometry={nodes.mesh676558152.geometry} material={materials.mat12} />
          <mesh name="mesh676558152_1" geometry={nodes.mesh676558152_1.geometry} material={materials.mat6} />
          <mesh name="mesh676558152_2" geometry={nodes.mesh676558152_2.geometry} material={materials.mat16} />
        </group>
        <mesh name="group1053331229" geometry={nodes.group1053331229.geometry} material={materials.mat16} />
        <mesh name="group1752120256" geometry={nodes.group1752120256.geometry} material={materials.mat2} />
        <mesh name="group390122617" geometry={nodes.group390122617.geometry} material={materials.mat2} />
        <mesh name="group1194867214" geometry={nodes.group1194867214.geometry} material={materials.mat2} />
        <mesh name="group1237680604" geometry={nodes.group1237680604.geometry} material={materials.mat2} />
        <mesh name="group308760357" geometry={nodes.group308760357.geometry} material={materials.mat18} />
        <mesh name="group39295081" geometry={nodes.group39295081.geometry} material={materials.mat18} />
        <mesh name="group595557110" geometry={nodes.group595557110.geometry} material={materials.mat18} />
        <mesh name="group963697911" geometry={nodes.group963697911.geometry} material={materials.mat18} />
        <mesh name="group469996019" geometry={nodes.group469996019.geometry} material={materials.mat18} />
        <mesh name="group219103445" geometry={nodes.group219103445.geometry} material={materials.mat18} />
        <mesh name="group306285786" geometry={nodes.group306285786.geometry} material={materials.mat18} />
        <mesh name="group1909001179" geometry={nodes.group1909001179.geometry} material={materials.mat18} />
        <mesh name="group402650929" geometry={nodes.group402650929.geometry} material={materials.mat18} />
        <mesh name="group1503235509" geometry={nodes.group1503235509.geometry} material={materials.mat14} />
        <mesh name="group642123494" geometry={nodes.group642123494.geometry} material={materials.mat14} />
        <mesh name="group1643420536" geometry={nodes.group1643420536.geometry} material={materials.mat2} />
        <mesh name="group759333935" geometry={nodes.group759333935.geometry} material={materials.mat7} />
        <mesh name="group1833379398" geometry={nodes.group1833379398.geometry} material={materials.mat15} />
        <mesh name="group1219882469" geometry={nodes.group1219882469.geometry} material={materials.mat20} />
        <group name="group1569413968">
          <mesh name="mesh1569413968" geometry={nodes.mesh1569413968.geometry} material={materials.mat10} />
          <mesh name="mesh1569413968_1" geometry={nodes.mesh1569413968_1.geometry} material={materials.mat13} />
          <mesh name="mesh1569413968_2" geometry={nodes.mesh1569413968_2.geometry} material={materials.mat4} />
        </group>
        <mesh name="group545945156" geometry={nodes.group545945156.geometry} material={materials.mat19} />
        <mesh name="group900368980" geometry={nodes.group900368980.geometry} material={materials.mat3} />
        <mesh name="group781204852" geometry={nodes.group781204852.geometry} material={materials.mat3} />
        <mesh name="group866268704" geometry={nodes.group866268704.geometry} material={materials.mat3} />
        <mesh name="group228676126" geometry={nodes.group228676126.geometry} material={materials.mat3} />
        <mesh name="group952569421" geometry={nodes.group952569421.geometry} material={materials.mat3} />
        <mesh name="group1332691708" geometry={nodes.group1332691708.geometry} material={materials.mat3} />
        <mesh name="group1978864617" geometry={nodes.group1978864617.geometry} material={materials.mat3} />
        <mesh name="group332407064" geometry={nodes.group332407064.geometry} material={materials.mat3} />
        <mesh name="group1714672003" geometry={nodes.group1714672003.geometry} material={materials.mat3} />
        <mesh name="group902987557" geometry={nodes.group902987557.geometry} material={materials.mat3} />
        <mesh name="group189065125" geometry={nodes.group189065125.geometry} material={materials.mat3} />
        <mesh name="group856587613" geometry={nodes.group856587613.geometry} material={materials.mat3} />
        <mesh name="group1367033778" geometry={nodes.group1367033778.geometry} material={materials.mat3} />
        <mesh name="group1932401182" geometry={nodes.group1932401182.geometry} material={materials.mat3} />
        <mesh name="group1092813159" geometry={nodes.group1092813159.geometry} material={materials.mat8} />
        <mesh name="group90905418" geometry={nodes.group90905418.geometry} material={materials.mat8} />
        <mesh name="group1071661591" geometry={nodes.group1071661591.geometry} material={materials.mat8} />
        <mesh name="group1738441144" geometry={nodes.group1738441144.geometry} material={materials.mat8} />
        <mesh name="group1540958086" geometry={nodes.group1540958086.geometry} material={materials.mat8} />
        <mesh name="group1499286270" geometry={nodes.group1499286270.geometry} material={materials.mat8} />
        <mesh name="group1523448264" geometry={nodes.group1523448264.geometry} material={materials.mat8} />
        <mesh name="group1604598374" geometry={nodes.group1604598374.geometry} material={materials.mat8} />
        <mesh name="group1188263133" geometry={nodes.group1188263133.geometry} material={materials.mat8} />
        <mesh name="group774631724" geometry={nodes.group774631724.geometry} material={materials.mat8} />
        <mesh name="group56013104" geometry={nodes.group56013104.geometry} material={materials.mat8} />
        <mesh name="group178770645" geometry={nodes.group178770645.geometry} material={materials.mat8} />
        <mesh name="group1141888760" geometry={nodes.group1141888760.geometry} material={materials.mat8} />
        <mesh name="group1806273415" geometry={nodes.group1806273415.geometry} material={materials.mat8} />
        <mesh name="group1348765653" geometry={nodes.group1348765653.geometry} material={materials.mat8} />
        <group name="group1641489903">
          <mesh name="mesh1641489903" geometry={nodes.mesh1641489903.geometry} material={materials.mat8} />
          <mesh name="mesh1641489903_1" geometry={nodes.mesh1641489903_1.geometry} material={materials.mat3} />
        </group>
        <group name="group1581773443">
          <mesh name="mesh1581773443" geometry={nodes.mesh1581773443.geometry} material={materials.mat3} />
          <mesh name="mesh1581773443_1" geometry={nodes.mesh1581773443_1.geometry} material={materials.mat8} />
        </group>
        <group name="group1462187575">
          <mesh name="mesh1462187575" geometry={nodes.mesh1462187575.geometry} material={materials.mat3} />
          <mesh name="mesh1462187575_1" geometry={nodes.mesh1462187575_1.geometry} material={materials.mat8} />
        </group>
        <mesh name="group651857968" geometry={nodes.group651857968.geometry} material={materials.mat8} />
        <mesh name="group1880427034" geometry={nodes.group1880427034.geometry} material={materials.mat8} />
        <mesh name="group1766949960" geometry={nodes.group1766949960.geometry} material={materials.mat7} />
        <mesh name="group23998760" geometry={nodes.group23998760.geometry} material={materials.mat7} />
        <mesh name="group257320616" geometry={nodes.group257320616.geometry} material={materials.mat15} />
        <mesh name="group840381656" geometry={nodes.group840381656.geometry} material={materials.mat13} />
        <mesh name="group620316437" geometry={nodes.group620316437.geometry} material={materials.mat13} />
        <mesh name="group865222195" geometry={nodes.group865222195.geometry} material={materials.mat13} />
        <mesh name="group730837410" geometry={nodes.group730837410.geometry} material={materials.mat6} />
        <mesh name="group1027791352" geometry={nodes.group1027791352.geometry} material={materials.mat6} />
        <mesh name="group307989858" geometry={nodes.group307989858.geometry} material={materials.mat6} />
        <mesh name="group1144655713" geometry={nodes.group1144655713.geometry} material={materials.mat6} />
        <mesh name="group2009595080" geometry={nodes.group2009595080.geometry} material={materials.mat6} />
        <mesh name="group1756705620" geometry={nodes.group1756705620.geometry} material={materials.mat6} />
        <mesh name="group1581661086" geometry={nodes.group1581661086.geometry} material={materials.mat6} />
        <mesh name="group484370377" geometry={nodes.group484370377.geometry} material={materials.mat6} />
        <mesh name="group1714945889" geometry={nodes.group1714945889.geometry} material={materials.mat6} />
        <mesh name="group1497521080" geometry={nodes.group1497521080.geometry} material={materials.mat6} />
        <mesh name="group1108635992" geometry={nodes.group1108635992.geometry} material={materials.mat6} />
        <mesh name="group1469021680" geometry={nodes.group1469021680.geometry} material={materials.mat6} />
        <mesh name="group1473708752" geometry={nodes.group1473708752.geometry} material={materials.mat6} />
        <mesh name="group1207470232" geometry={nodes.group1207470232.geometry} material={materials.mat6} />
        <mesh name="group266128581" geometry={nodes.group266128581.geometry} material={materials.mat6} />
        <mesh name="group220053028" geometry={nodes.group220053028.geometry} material={materials.mat6} />
        <mesh name="group716105814" geometry={nodes.group716105814.geometry} material={materials.mat15} />
        <mesh name="group1593613913" geometry={nodes.group1593613913.geometry} material={materials.mat15} />
        <mesh name="group1222437788" geometry={nodes.group1222437788.geometry} material={materials.mat15} />
        <mesh name="group2132910191" geometry={nodes.group2132910191.geometry} material={materials.mat3} />
        <mesh name="group85898500" geometry={nodes.group85898500.geometry} material={materials.mat3} />
        <mesh name="group86393190" geometry={nodes.group86393190.geometry} material={materials.mat12} />
        <mesh name="group1382287371" geometry={nodes.group1382287371.geometry} material={materials.mat12} />
        <mesh name="group1439635812" geometry={nodes.group1439635812.geometry} material={materials.mat7} />
        <group name="group2033216695">
          <mesh name="mesh2033216695" geometry={nodes.mesh2033216695.geometry} material={materials.mat7} />
          <mesh name="mesh2033216695_1" geometry={nodes.mesh2033216695_1.geometry} material={materials.mat15} />
        </group>
        <group name="group872839425">
          <mesh name="mesh872839425" geometry={nodes.mesh872839425.geometry} material={materials.mat15} />
          <mesh name="mesh872839425_1" geometry={nodes.mesh872839425_1.geometry} material={materials.mat7} />
        </group>
        <group name="group1513056428">
          <mesh name="mesh1513056428" geometry={nodes.mesh1513056428.geometry} material={materials.mat15} />
          <mesh name="mesh1513056428_1" geometry={nodes.mesh1513056428_1.geometry} material={materials.mat7} />
        </group>
        <group name="group2107200194">
          <mesh name="mesh2107200194" geometry={nodes.mesh2107200194.geometry} material={materials.mat15} />
          <mesh name="mesh2107200194_1" geometry={nodes.mesh2107200194_1.geometry} material={materials.mat7} />
        </group>
        <group name="group842773834">
          <mesh name="mesh842773834" geometry={nodes.mesh842773834.geometry} material={materials.mat15} />
          <mesh name="mesh842773834_1" geometry={nodes.mesh842773834_1.geometry} material={materials.mat7} />
        </group>
        <mesh name="group941049133" geometry={nodes.group941049133.geometry} material={materials.mat10} />
        <mesh name="group163031802" geometry={nodes.group163031802.geometry} material={materials.mat10} />
        <mesh name="group1679570353" geometry={nodes.group1679570353.geometry} material={materials.mat10} />
        <mesh name="group946209829" geometry={nodes.group946209829.geometry} material={materials.mat10} />
        <mesh name="group1403162245" geometry={nodes.group1403162245.geometry} material={materials.mat10} />
        <mesh name="group1777963046" geometry={nodes.group1777963046.geometry} material={materials.mat10} />
        <mesh name="group2069658298" geometry={nodes.group2069658298.geometry} material={materials.mat10} />
        <mesh name="group890088657" geometry={nodes.group890088657.geometry} material={materials.mat10} />
        <mesh name="group1091540372" geometry={nodes.group1091540372.geometry} material={materials.mat2} />
        <mesh name="group204137803" geometry={nodes.group204137803.geometry} material={materials.mat2} />
        <mesh name="group2022482304" geometry={nodes.group2022482304.geometry} material={materials.mat2} />
        <mesh name="group1578200380" geometry={nodes.group1578200380.geometry} material={materials.mat2} />
        <mesh name="group238242423" geometry={nodes.group238242423.geometry} material={materials.mat2} />
        <mesh name="group1742656630" geometry={nodes.group1742656630.geometry} material={materials.mat2} />
        <mesh name="group487077061" geometry={nodes.group487077061.geometry} material={materials.mat2} />
        <mesh name="group2048561999" geometry={nodes.group2048561999.geometry} material={materials.mat6} />
        <mesh name="group307702733" geometry={nodes.group307702733.geometry} material={materials.mat6} />
        <group name="group935951105">
          <mesh name="mesh935951105" geometry={nodes.mesh935951105.geometry} material={materials.mat6} />
          <mesh name="mesh935951105_1" geometry={nodes.mesh935951105_1.geometry} material={materials.mat3} />
        </group>
        <mesh name="group22780939" geometry={nodes.group22780939.geometry} material={materials.mat6} />
        <mesh name="group1476163393" geometry={nodes.group1476163393.geometry} material={materials.mat6} />
        <mesh name="group99640494" geometry={nodes.group99640494.geometry} material={materials.mat6} />
        <mesh name="group1338579614" geometry={nodes.group1338579614.geometry} material={materials.mat15} />
        <group name="group880128162">
          <mesh name="mesh880128162" geometry={nodes.mesh880128162.geometry} material={materials.mat13} />
          <mesh name="mesh880128162_1" geometry={nodes.mesh880128162_1.geometry} material={materials.mat11} />
          <mesh name="mesh880128162_2" geometry={nodes.mesh880128162_2.geometry} material={materials.mat22} />
        </group>
        <group name="group1571301754">
          <mesh name="mesh1571301754" geometry={nodes.mesh1571301754.geometry} material={materials.mat22} />
          <mesh name="mesh1571301754_1" geometry={nodes.mesh1571301754_1.geometry} material={materials.mat11} />
        </group>
        <group name="group1452230727">
          <mesh name="mesh1452230727" geometry={nodes.mesh1452230727.geometry} material={materials.mat22} />
          <mesh name="mesh1452230727_1" geometry={nodes.mesh1452230727_1.geometry} material={materials.mat13} />
          <mesh name="mesh1452230727_2" geometry={nodes.mesh1452230727_2.geometry} material={materials.mat11} />
        </group>
        <group name="group970764617">
          <mesh name="mesh970764617" geometry={nodes.mesh970764617.geometry} material={materials.mat9} />
          <mesh name="mesh970764617_1" geometry={nodes.mesh970764617_1.geometry} material={materials.mat13} />
        </group>
        <group name="group1103955063">
          <mesh name="mesh1103955063" geometry={nodes.mesh1103955063.geometry} material={materials.mat13} />
          <mesh name="mesh1103955063_1" geometry={nodes.mesh1103955063_1.geometry} material={materials.mat9} />
        </group>
        <group name="group234630948">
          <mesh name="mesh234630948" geometry={nodes.mesh234630948.geometry} material={materials.mat13} />
          <mesh name="mesh234630948_1" geometry={nodes.mesh234630948_1.geometry} material={materials.mat9} />
        </group>
        <group name="group860925790">
          <mesh name="mesh860925790" geometry={nodes.mesh860925790.geometry} material={materials.mat13} />
          <mesh name="mesh860925790_1" geometry={nodes.mesh860925790_1.geometry} material={materials.mat9} />
        </group>
        <mesh name="group1341945882" geometry={nodes.group1341945882.geometry} material={materials.mat13} />
        <mesh name="group2001963217" geometry={nodes.group2001963217.geometry} material={materials.mat9} />
        <mesh name="group1454617081" geometry={nodes.group1454617081.geometry} material={materials.mat12} />
        <mesh name="group565449673" geometry={nodes.group565449673.geometry} material={materials.mat14} />
        <mesh name="group618592561" geometry={nodes.group618592561.geometry} material={materials.mat13} />
        <group name="group2062267188">
          <mesh name="mesh2062267188" geometry={nodes.mesh2062267188.geometry} material={materials.mat5} />
          <mesh name="mesh2062267188_1" geometry={nodes.mesh2062267188_1.geometry} material={materials.mat15} />
        </group>
        <group name="group395040991">
          <mesh name="mesh395040991" geometry={nodes.mesh395040991.geometry} material={materials.mat5} />
          <mesh name="mesh395040991_1" geometry={nodes.mesh395040991_1.geometry} material={materials.mat1} />
        </group>
        <group name="group1856870417">
          <mesh name="mesh1856870417" geometry={nodes.mesh1856870417.geometry} material={materials.mat5} />
          <mesh name="mesh1856870417_1" geometry={nodes.mesh1856870417_1.geometry} material={materials.mat7} />
        </group>
        <group name="group1742115893">
          <mesh name="mesh1742115893" geometry={nodes.mesh1742115893.geometry} material={materials.mat5} />
          <mesh name="mesh1742115893_1" geometry={nodes.mesh1742115893_1.geometry} material={materials.mat10} />
        </group>
        <group name="group1955694657">
          <mesh name="mesh1955694657" geometry={nodes.mesh1955694657.geometry} material={materials.mat5} />
          <mesh name="mesh1955694657_1" geometry={nodes.mesh1955694657_1.geometry} material={materials.mat11} />
        </group>
        <group name="group568651757">
          <mesh name="mesh568651757" geometry={nodes.mesh568651757.geometry} material={materials.mat5} />
          <mesh name="mesh568651757_1" geometry={nodes.mesh568651757_1.geometry} material={materials.mat3} />
        </group>
        <group name="group1823463482">
          <mesh name="mesh1823463482" geometry={nodes.mesh1823463482.geometry} material={materials.mat5} />
          <mesh name="mesh1823463482_1" geometry={nodes.mesh1823463482_1.geometry} material={materials.mat19} />
        </group>
        <group name="group1103235028">
          <mesh name="mesh1103235028" geometry={nodes.mesh1103235028.geometry} material={materials.mat5} />
          <mesh name="mesh1103235028_1" geometry={nodes.mesh1103235028_1.geometry} material={materials.mat13} />
        </group>
        <group name="group1635959395">
          <mesh name="mesh1635959395" geometry={nodes.mesh1635959395.geometry} material={materials.mat5} />
          <mesh name="mesh1635959395_1" geometry={nodes.mesh1635959395_1.geometry} material={materials.mat9} />
        </group>
        <group name="group1536213894">
          <mesh name="mesh1536213894" geometry={nodes.mesh1536213894.geometry} material={materials.mat5} />
          <mesh name="mesh1536213894_1" geometry={nodes.mesh1536213894_1.geometry} material={materials.mat14} />
        </group>
        <group name="group461107475">
          <mesh name="mesh461107475" geometry={nodes.mesh461107475.geometry} material={materials.mat5} />
          <mesh name="mesh461107475_1" geometry={nodes.mesh461107475_1.geometry} material={materials.mat1} />
        </group>
        <group name="group534372791">
          <mesh name="mesh534372791" geometry={nodes.mesh534372791.geometry} material={materials.mat5} />
          <mesh name="mesh534372791_1" geometry={nodes.mesh534372791_1.geometry} material={materials.mat12} />
        </group>
        <group name="group1675421008">
          <mesh name="mesh1675421008" geometry={nodes.mesh1675421008.geometry} material={materials.mat16} />
          <mesh name="mesh1675421008_1" geometry={nodes.mesh1675421008_1.geometry} material={materials.mat20} />
        </group>
        <group name="group1837669520">
          <mesh name="mesh1837669520" geometry={nodes.mesh1837669520.geometry} material={materials.mat20} />
          <mesh name="mesh1837669520_1" geometry={nodes.mesh1837669520_1.geometry} material={materials.mat16} />
        </group>
        <mesh name="group1551347828" geometry={nodes.group1551347828.geometry} material={materials.mat19} />
        <mesh name="group1243373000" geometry={nodes.group1243373000.geometry} material={materials.mat19} />
        <mesh name="group1780659953" geometry={nodes.group1780659953.geometry} material={materials.mat19} />
        <mesh name="group2037377278" geometry={nodes.group2037377278.geometry} material={materials.mat19} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/city.glb')
